let data = [
  {
    value: "41962.5",
    timedValue: [
      {
        value: "30083.3",
        time: "1"
      }, {
        value: "30166.7",
        time: "2"
      }, {
        value: "30250",
        time: "3"
      }, {
        value: "30333.3",
        time: "4"
      }, {
        value: "30416.7",
        time: "5"
      }, {
        value: "30500",
        time: "6"
      }, {
        value: "30583.3",
        time: "7"
      }, {
        value: "30666.7",
        time: "8"
      }, {
        value: "30750",
        time: "9"
      }, {
        value: "30833.3",
        time: "10"
      }, {
        value: "30916.7",
        time: "11"
      }, {
        value: "41850",
        time: "12"
      }, {
        value: "41962.5",
        time: "13"
      }],
    name: "_Баланс 110: Основные средства"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 120: Нематериальные активы"
  }, {
    value: "14962.5",
    timedValue: [
      {
        value: "10083.3",
        time: "1"
      }, {
        value: "10166.7",
        time: "2"
      }, {
        value: "10250",
        time: "3"
      }, {
        value: "10333.3",
        time: "4"
      }, {
        value: "10416.7",
        time: "5"
      }, {
        value: "10500",
        time: "6"
      }, {
        value: "10583.3",
        time: "7"
      }, {
        value: "10666.7",
        time: "8"
      }, {
        value: "10750",
        time: "9"
      }, {
        value: "10833.3",
        time: "10"
      }, {
        value: "10916.7",
        time: "11"
      }, {
        value: "14850",
        time: "12"
      }, {
        value: "14962.5",
        time: "13"
      }],
    name: "_Баланс 130: Доходные вложения в материальные ценности"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 140: Вложения во внеоборотные активы"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 150: Прочие внеоборотные активы"
  }, {
    value: "56925",
    timedValue: [
      {
        value: "40166.7",
        time: "1"
      }, {
        value: "40333.3",
        time: "2"
      }, {
        value: "40500",
        time: "3"
      }, {
        value: "40666.7",
        time: "4"
      }, {
        value: "40833.3",
        time: "5"
      }, {
        value: "41000",
        time: "6"
      }, {
        value: "41166.7",
        time: "7"
      }, {
        value: "41333.3",
        time: "8"
      }, {
        value: "41500",
        time: "9"
      }, {
        value: "41666.7",
        time: "10"
      }, {
        value: "41833.3",
        time: "11"
      }, {
        value: "56700",
        time: "12"
      }, {
        value: "56925",
        time: "13"
      }],
    name: "_Баланс 190: ИТОГО ВНЕОБОРОТНЫЕ АКТИВЫ"
  }, {
    value: "3906.84",
    timedValue: [
      {
        value: "10242.2",
        time: "1"
      }, {
        value: "8215.5",
        time: "2"
      }, {
        value: "7312.33",
        time: "3"
      }, {
        value: "6716.7",
        time: "4"
      }, {
        value: "6491.71",
        time: "5"
      }, {
        value: "5793.93",
        time: "6"
      }, {
        value: "4206.97",
        time: "7"
      }, {
        value: "2763.92",
        time: "8"
      }, {
        value: "1942.82",
        time: "9"
      }, {
        value: "1463.27",
        time: "10"
      }, {
        value: "1285.31",
        time: "11"
      }, {
        value: "2558.31",
        time: "12"
      }, {
        value: "3906.84",
        time: "13"
      }],
    name: "_Баланс 210: Запасы"
  }, {
    value: "-3068.69",
    timedValue: [
      {
        value: "2693",
        time: "1"
      }, {
        value: "2030",
        time: "2"
      }, {
        value: "1220",
        time: "3"
      }, {
        value: "1172.06",
        time: "4"
      }, {
        value: "1103.36",
        time: "5"
      }, {
        value: "109.829",
        time: "6"
      }, {
        value: "-1737.22",
        time: "7"
      }, {
        value: "-2442.94",
        time: "8"
      }, {
        value: "-3046.1",
        time: "9"
      }, {
        value: "-3068.69",
        time: "10"
      }, {
        value: "-3068.69",
        time: "11"
      }, {
        value: "-3068.69",
        time: "12"
      }, {
        value: "-3068.69",
        time: "13"
      }],
    name: "_Баланс 211: сырье, материалы и другие аналогичные ценности"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 212: животные на выращивании и откорме"
  }, {
    value: "6975.53",
    timedValue: [
      {
        value: "7549.17",
        time: "1"
      }, {
        value: "6185.5",
        time: "2"
      }, {
        value: "6092.33",
        time: "3"
      }, {
        value: "5544.63",
        time: "4"
      }, {
        value: "5388.35",
        time: "5"
      }, {
        value: "5684.1",
        time: "6"
      }, {
        value: "5944.19",
        time: "7"
      }, {
        value: "5206.86",
        time: "8"
      }, {
        value: "4988.91",
        time: "9"
      }, {
        value: "4531.97",
        time: "10"
      }, {
        value: "4354",
        time: "11"
      }, {
        value: "5627",
        time: "12"
      }, {
        value: "6975.53",
        time: "13"
      }],
    name: "_Баланс 213: Незавершенное производство (издержки обращения)"
  }, {
    value: "13472.6",
    timedValue: [
      {
        value: "9990.13",
        time: "1"
      }, {
        value: "10306",
        time: "2"
      }, {
        value: "10770.9",
        time: "3"
      }, {
        value: "11009.9",
        time: "4"
      }, {
        value: "11159.3",
        time: "5"
      }, {
        value: "11665.7",
        time: "6"
      }, {
        value: "12213.3",
        time: "7"
      }, {
        value: "12587.6",
        time: "8"
      }, {
        value: "12982.7",
        time: "9"
      }, {
        value: "12986.8",
        time: "10"
      }, {
        value: "12986.8",
        time: "11"
      }, {
        value: "13268.7",
        time: "12"
      }, {
        value: "13472.6",
        time: "13"
      }],
    name: "_Баланс 220: Налоги по приобретенным ценностям"
  }, {
    value: "39317.6",
    timedValue: [
      {
        value: "5525",
        time: "1"
      }, {
        value: "10420",
        time: "2"
      }, {
        value: "14309.6",
        time: "3"
      }, {
        value: "16468.3",
        time: "4"
      }, {
        value: "18864.5",
        time: "5"
      }, {
        value: "21967.1",
        time: "6"
      }, {
        value: "27970.6",
        time: "7"
      }, {
        value: "32438.7",
        time: "8"
      }, {
        value: "35774.7",
        time: "9"
      }, {
        value: "37856.7",
        time: "10"
      }, {
        value: "39317.6",
        time: "11"
      }, {
        value: "39317.6",
        time: "12"
      }, {
        value: "39317.6",
        time: "13"
      }],
    name: "_Баланс 230: Готовая продукция и товары"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 240: Товары отгруженные, выполненные работы, оказанные услуги"
  }, {
    value: "5000",
    timedValue: [
      {
        value: "5000",
        time: "1"
      }, {
        value: "5000",
        time: "2"
      }, {
        value: "5000",
        time: "3"
      }, {
        value: "5000",
        time: "4"
      }, {
        value: "5000",
        time: "5"
      }, {
        value: "5000",
        time: "6"
      }, {
        value: "5000",
        time: "7"
      }, {
        value: "5000",
        time: "8"
      }, {
        value: "5000",
        time: "9"
      }, {
        value: "5000",
        time: "10"
      }, {
        value: "5000",
        time: "11"
      }, {
        value: "5000",
        time: "12"
      }, {
        value: "5000",
        time: "13"
      }],
    name: "_Баланс 251: Дебиторская задолженность расчеты с покупателями и заказчиками"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 252: Расчеты с учредителями по вкладам в уставный фонд"
  }, {
    value: "5000",
    timedValue: [
      {
        value: "5000",
        time: "1"
      }, {
        value: "5000",
        time: "2"
      }, {
        value: "5000",
        time: "3"
      }, {
        value: "5000",
        time: "4"
      }, {
        value: "5000",
        time: "5"
      }, {
        value: "5000",
        time: "6"
      }, {
        value: "5000",
        time: "7"
      }, {
        value: "5000",
        time: "8"
      }, {
        value: "5000",
        time: "9"
      }, {
        value: "5000",
        time: "10"
      }, {
        value: "5000",
        time: "11"
      }, {
        value: "5000",
        time: "12"
      }, {
        value: "5000",
        time: "13"
      }],
    name: "_Баланс 253: Дебиторская задолженность расчеты с разными дебиторами и кредиторами"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 260: Краткосрочне финансовые вложения"
  }, {
    value: "-82728.1",
    timedValue: [
      {
        value: "5059.2",
        time: "1"
      }, {
        value: "-16726",
        time: "2"
      }, {
        value: "-22706",
        time: "3"
      }, {
        value: "-27516.8",
        time: "4"
      }, {
        value: "-29477.4",
        time: "5"
      }, {
        value: "-38266",
        time: "6"
      }, {
        value: "-43839.8",
        time: "7"
      }, {
        value: "-50462",
        time: "8"
      }, {
        value: "-56960.9",
        time: "9"
      }, {
        value: "-57232.8",
        time: "10"
      }, {
        value: "-63102.3",
        time: "11"
      }, {
        value: "-74734.7",
        time: "12"
      }, {
        value: "-82728.1",
        time: "13"
      }],
    name: "_Баланс 270: Денежные средства"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 280: Прочие оборотные активы"
  }, {
    value: "-16031.1",
    timedValue: [
      {
        value: "40816.5",
        time: "1"
      }, {
        value: "22215.5",
        time: "2"
      }, {
        value: "19686.8",
        time: "3"
      }, {
        value: "16678.1",
        time: "4"
      }, {
        value: "17038",
        time: "5"
      }, {
        value: "11160.7",
        time: "6"
      }, {
        value: "10551.1",
        time: "7"
      }, {
        value: "7328.27",
        time: "8"
      }, {
        value: "3739.29",
        time: "9"
      }, {
        value: "5074.04",
        time: "10"
      }, {
        value: "487.485",
        time: "11"
      }, {
        value: "-9590.08",
        time: "12"
      }, {
        value: "-16031.1",
        time: "13"
      }],
    name: "_Баланс 290: ИТОГО ОБОРОТНЫЕ АКТИВЫ"
  }, {
    value: "0",
    name: "_Баланс 299: Баланс АКТИВОВ"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 510: Уставный фонд (капитал)"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 520: Резервный фонд"
  }, {
    value: "6575",
    timedValue: [
      {
        value: "5000",
        time: "1"
      }, {
        value: "5000",
        time: "2"
      }, {
        value: "5000",
        time: "3"
      }, {
        value: "5000",
        time: "4"
      }, {
        value: "5000",
        time: "5"
      }, {
        value: "5000",
        time: "6"
      }, {
        value: "5000",
        time: "7"
      }, {
        value: "5000",
        time: "8"
      }, {
        value: "5000",
        time: "9"
      }, {
        value: "5000",
        time: "10"
      }, {
        value: "5000",
        time: "11"
      }, {
        value: "6575",
        time: "12"
      }, {
        value: "6575",
        time: "13"
      }],
    name: "_Баланс 530: Добавочный фонд"
  }, {
    value: "6575",
    timedValue: [
      {
        value: "5000",
        time: "1"
      }, {
        value: "5000",
        time: "2"
      }, {
        value: "5000",
        time: "3"
      }, {
        value: "5000",
        time: "4"
      }, {
        value: "5000",
        time: "5"
      }, {
        value: "5000",
        time: "6"
      }, {
        value: "5000",
        time: "7"
      }, {
        value: "5000",
        time: "8"
      }, {
        value: "5000",
        time: "9"
      }, {
        value: "5000",
        time: "10"
      }, {
        value: "5000",
        time: "11"
      }, {
        value: "6575",
        time: "12"
      }, {
        value: "6575",
        time: "13"
      }],
    name: "_Баланс 540: Нераспределенная прибыль"
  }, {
    value: "6575",
    timedValue: [
      {
        value: "5000",
        time: "1"
      }, {
        value: "5000",
        time: "2"
      }, {
        value: "5000",
        time: "3"
      }, {
        value: "5000",
        time: "4"
      }, {
        value: "5000",
        time: "5"
      }, {
        value: "5000",
        time: "6"
      }, {
        value: "5000",
        time: "7"
      }, {
        value: "5000",
        time: "8"
      }, {
        value: "5000",
        time: "9"
      }, {
        value: "5000",
        time: "10"
      }, {
        value: "5000",
        time: "11"
      }, {
        value: "6575",
        time: "12"
      }, {
        value: "6575",
        time: "13"
      }],
    name: "_Баланс 550: Непокрытый убыток"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 560: Целевое финансирование"
  }, {
    value: "40893.9",
    timedValue: [
      {
        value: "15000",
        time: "1"
      }, {
        value: "15000",
        time: "2"
      }, {
        value: "15000",
        time: "3"
      }, {
        value: "15000",
        time: "4"
      }, {
        value: "15000",
        time: "5"
      }, {
        value: "15000",
        time: "6"
      }, {
        value: "15000",
        time: "7"
      }, {
        value: "15000",
        time: "8"
      }, {
        value: "15000",
        time: "9"
      }, {
        value: "15000",
        time: "10"
      }, {
        value: "15000",
        time: "11"
      }, {
        value: "19725",
        time: "12"
      }, {
        value: "19725",
        time: "13"
      }],
    name: "_Баланс 590: ИТОГО СОБСТВЕННЫЙ КАПИТАЛ"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 610: Резервы предстоящих расходов"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 620: Расходы будущих периодов"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 630: Доходы будущих периодов"
  }, {
    value: "3921.91",
    timedValue: [
      {
        value: "-6437.52",
        time: "1"
      }, {
        value: "-0.034722",
        time: "2"
      }, {
        value: "1131.47",
        time: "3"
      }, {
        value: "682.586",
        time: "4"
      }, {
        value: "1076.66",
        time: "5"
      }, {
        value: "1049.3",
        time: "6"
      }, {
        value: "1737.9",
        time: "7"
      }, {
        value: "1568.73",
        time: "8"
      }, {
        value: "2067.58",
        time: "9"
      }, {
        value: "2371.04",
        time: "10"
      }, {
        value: "2277.95",
        time: "11"
      }, {
        value: "3034.83",
        time: "12"
      }, {
        value: "3921.91",
        time: "13"
      }],
    name: "_Баланс 640: Прибыль отчетного года"
  }, {
    value: "3921.91",
    timedValue: [
      {
        value: "-6437.52",
        time: "1"
      }, {
        value: "-0.034722",
        time: "2"
      }, {
        value: "1131.47",
        time: "3"
      }, {
        value: "682.586",
        time: "4"
      }, {
        value: "1076.66",
        time: "5"
      }, {
        value: "1049.3",
        time: "6"
      }, {
        value: "1737.9",
        time: "7"
      }, {
        value: "1568.73",
        time: "8"
      }, {
        value: "2067.58",
        time: "9"
      }, {
        value: "2371.04",
        time: "10"
      }, {
        value: "2277.95",
        time: "11"
      }, {
        value: "3034.83",
        time: "12"
      }, {
        value: "3921.91",
        time: "13"
      }],
    name: "_Баланс 650: Убыток отчетного года"
  }, {
    value: "7843.81",
    timedValue: [
      {
        value: "-12875",
        time: "1"
      }, {
        value: "-0.069444",
        time: "2"
      }, {
        value: "2262.95",
        time: "3"
      }, {
        value: "1365.17",
        time: "4"
      }, {
        value: "2153.32",
        time: "5"
      }, {
        value: "2098.61",
        time: "6"
      }, {
        value: "3475.8",
        time: "7"
      }, {
        value: "3137.46",
        time: "8"
      }, {
        value: "4135.16",
        time: "9"
      }, {
        value: "4742.08",
        time: "10"
      }, {
        value: "4555.9",
        time: "11"
      }, {
        value: "6069.66",
        time: "12"
      }, {
        value: "7843.81",
        time: "13"
      }],
    name: "_Баланс 690: ИТОГО ДОЛГОСРОЧНЫЕ ОБЯЗАТЕЛЬСТВА"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 710: Краткосрочные кредиты и займы"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 720: Долгосрочные кредиты и займы"
  }, {
    value: "8960.34",
    timedValue: [
      {
        value: "5990",
        time: "1"
      }, {
        value: "6563.16",
        time: "2"
      }, {
        value: "6154.18",
        time: "3"
      }, {
        value: "6237.31",
        time: "4"
      }, {
        value: "6650.69",
        time: "5"
      }, {
        value: "6103.67",
        time: "6"
      }, {
        value: "6262.38",
        time: "7"
      }, {
        value: "6418.86",
        time: "8"
      }, {
        value: "6215.85",
        time: "9"
      }, {
        value: "7565.32",
        time: "10"
      }, {
        value: "8808.28",
        time: "11"
      }, {
        value: "8637.68",
        time: "12"
      }, {
        value: "8960.34",
        time: "13"
      }],
    name: "_Баланс 731: Кредиторская задолженность, поставщики и подрядчики"
  }, {
    value: "5013.56",
    timedValue: [
      {
        value: "5010",
        time: "1"
      }, {
        value: "5537.25",
        time: "2"
      }, {
        value: "5128.27",
        time: "3"
      }, {
        value: "5156.75",
        time: "4"
      }, {
        value: "5019.12",
        time: "5"
      }, {
        value: "5023.12",
        time: "6"
      }, {
        value: "5181.83",
        time: "7"
      }, {
        value: "5338.31",
        time: "8"
      }, {
        value: "5135.94",
        time: "9"
      }, {
        value: "5123.17",
        time: "10"
      }, {
        value: "5139.83",
        time: "11"
      }, {
        value: "5012.51",
        time: "12"
      }, {
        value: "5013.56",
        time: "13"
      }],
    name: "_Баланс 732: Кредиторская задолженность, расчеты по оплате труда"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 733: Кредиторская задолженность, расчеты по прочим операциям с персоналом"
  }, {
    value: "3180.68",
    timedValue: [
      {
        value: "6795.84",
        time: "1"
      }, {
        value: "754.607",
        time: "2"
      }, {
        value: "847.205",
        time: "3"
      }, {
        value: "1203.05",
        time: "4"
      }, {
        value: "2332.79",
        time: "5"
      }, {
        value: "1431.28",
        time: "6"
      }, {
        value: "1550.78",
        time: "7"
      }, {
        value: "1786.47",
        time: "8"
      }, {
        value: "2454.38",
        time: "9"
      }, {
        value: "4492.02",
        time: "10"
      }, {
        value: "4087.38",
        time: "11"
      }, {
        value: "2760.91",
        time: "12"
      }, {
        value: "3180.68",
        time: "13"
      }],
    name: "_Баланс 734: Кредиторская задолженность, расчеты по налогам и сборам"
  }, {
    value: "9.12429",
    timedValue: [
      {
        value: "5003.5",
        time: "1"
      }, {
        value: "188.038",
        time: "2"
      }, {
        value: "44.895",
        time: "3"
      }, {
        value: "54.8632",
        time: "4"
      }, {
        value: "61.5558",
        time: "5"
      }, {
        value: "8.09031",
        time: "6"
      }, {
        value: "63.6398",
        time: "7"
      }, {
        value: "118.409",
        time: "8"
      }, {
        value: "165.763",
        time: "9"
      }, {
        value: "208.871",
        time: "10"
      }, {
        value: "5.83082",
        time: "11"
      }, {
        value: "4.37965",
        time: "12"
      }, {
        value: "9.12429",
        time: "13"
      }],
    name: "_Баланс 735: Кредиторская задолженность, по социальному страхованию и обеспечению"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Баланс 736: Кредиторская задолженность, расчеты с акционерами (учредителями) по выплате доходов (дивидендов)"
  }, {
    value: "5000",
    timedValue: [
      {
        value: "5000",
        time: "1"
      }, {
        value: "5000",
        time: "2"
      }, {
        value: "5000",
        time: "3"
      }, {
        value: "5000",
        time: "4"
      }, {
        value: "5000",
        time: "5"
      }, {
        value: "5000",
        time: "6"
      }, {
        value: "5000",
        time: "7"
      }, {
        value: "5000",
        time: "8"
      }, {
        value: "5000",
        time: "9"
      }, {
        value: "5000",
        time: "10"
      }, {
        value: "5000",
        time: "11"
      }, {
        value: "5000",
        time: "12"
      }, {
        value: "5000",
        time: "13"
      }],
    name: "_Баланс 737: Кредиторская задолженность, расчеты с разными дебиторами и кредиторами"
  }, {
    value: "22163.7",
    timedValue: [
      {
        value: "27799.3",
        time: "1"
      }, {
        value: "18043.1",
        time: "2"
      }, {
        value: "17174.6",
        time: "3"
      }, {
        value: "17652",
        time: "4"
      }, {
        value: "19064.2",
        time: "5"
      }, {
        value: "17566.2",
        time: "6"
      }, {
        value: "18058.6",
        time: "7"
      }, {
        value: "18662.1",
        time: "8"
      }, {
        value: "18971.9",
        time: "9"
      }, {
        value: "22389.4",
        time: "10"
      }, {
        value: "23041.3",
        time: "11"
      }, {
        value: "21415.5",
        time: "12"
      }, {
        value: "22163.7",
        time: "13"
      }],
    name: "_Баланс 790: ИТОГО Кредиторская задолженность"
  }, {
    value: "49732.5",
    timedValue: [
      {
        value: "29924.3",
        time: "1"
      }, {
        value: "33043",
        time: "2"
      }, {
        value: "34437.5",
        time: "3"
      }, {
        value: "34017.1",
        time: "4"
      }, {
        value: "36217.5",
        time: "5"
      }, {
        value: "34664.8",
        time: "6"
      }, {
        value: "36534.4",
        time: "7"
      }, {
        value: "36799.5",
        time: "8"
      }, {
        value: "38107.1",
        time: "9"
      }, {
        value: "42131.5",
        time: "10"
      }, {
        value: "42597.2",
        time: "11"
      }, {
        value: "47210.1",
        time: "12"
      }, {
        value: "49732.5",
        time: "13"
      }],
    name: "_Баланс 890: Баланс ПАССИВОВ"
  }, {
    value: "315334",
    timedValue: [
      {
        value: "5471.35",
        time: "1"
      }, {
        value: "18791.5",
        time: "2"
      }, {
        value: "34511.8",
        time: "3"
      }, {
        value: "50850.3",
        time: "4"
      }, {
        value: "68518.1",
        time: "5"
      }, {
        value: "90176.6",
        time: "6"
      }, {
        value: "114369",
        time: "7"
      }, {
        value: "139196",
        time: "8"
      }, {
        value: "167194",
        time: "9"
      }, {
        value: "195568",
        time: "10"
      }, {
        value: "228223",
        time: "11"
      }, {
        value: "268487",
        time: "12"
      }, {
        value: "315334",
        time: "13"
      }],
    name: "_Отчет о прибылях и убытках: Выручка (за минусом налогов)"
  }, {
    value: "13103.6",
    timedValue: [
      {
        value: "525",
        time: "1"
      }, {
        value: "1392.8",
        time: "2"
      }, {
        value: "3433.81",
        time: "3"
      }, {
        value: "3547.43",
        time: "4"
      }, {
        value: "4609.82",
        time: "5"
      }, {
        value: "6358.69",
        time: "6"
      }, {
        value: "10165.2",
        time: "7"
      }, {
        value: "11633.9",
        time: "8"
      }, {
        value: "13028.4",
        time: "9"
      }, {
        value: "13103.6",
        time: "10"
      }, {
        value: "13103.6",
        time: "11"
      }, {
        value: "13103.6",
        time: "12"
      }, {
        value: "13103.6",
        time: "13"
      }],
    name: "_Отчет о прибылях и убытках: Себестоимость"
  }, {
    value: "302230",
    timedValue: [
      {
        value: "4946.35",
        time: "1"
      }, {
        value: "17398.8",
        time: "2"
      }, {
        value: "31078",
        time: "3"
      }, {
        value: "47302.9",
        time: "4"
      }, {
        value: "63908.3",
        time: "5"
      }, {
        value: "83817.9",
        time: "6"
      }, {
        value: "104204",
        time: "7"
      }, {
        value: "127562",
        time: "8"
      }, {
        value: "154165",
        time: "9"
      }, {
        value: "182464",
        time: "10"
      }, {
        value: "215119",
        time: "11"
      }, {
        value: "255383",
        time: "12"
      }, {
        value: "302230",
        time: "13"
      }],
    name: "_Отчет о прибылях и убытках: Прибыль от реализации"
  }, {
    value: "872.536",
    timedValue: [
      {
        value: "1437.52",
        time: "1"
      }, {
        value: "0.0347222",
        time: "2"
      }, {
        value: "0.0338542",
        time: "3"
      }, {
        value: "325.323",
        time: "4"
      }, {
        value: "196.268",
        time: "5"
      }, {
        value: "309.564",
        time: "6"
      }, {
        value: "301.698",
        time: "7"
      }, {
        value: "499.67",
        time: "8"
      }, {
        value: "451.032",
        time: "9"
      }, {
        value: "594.453",
        time: "10"
      }, {
        value: "681.698",
        time: "11"
      }, {
        value: "654.933",
        time: "12"
      }, {
        value: "872.536",
        time: "13"
      }],
    name: "_Отчет о прибылях и убытках: Налог на прибыль и иные обязательные платежи"
  }, {
    value: "0",
    timedValue: [
      {
        value: "0",
        time: "1"
      }, {
        value: "0",
        time: "2"
      }, {
        value: "0",
        time: "3"
      }, {
        value: "0",
        time: "4"
      }, {
        value: "0",
        time: "5"
      }, {
        value: "0",
        time: "6"
      }, {
        value: "0",
        time: "7"
      }, {
        value: "0",
        time: "8"
      }, {
        value: "0",
        time: "9"
      }, {
        value: "0",
        time: "10"
      }, {
        value: "0",
        time: "11"
      }, {
        value: "0",
        time: "12"
      }, {
        value: "0",
        time: "13"
      }],
    name: "_Отчет о прибылях и убытках: Использовано прибыли"
  }, {
    value: "14688",
    timedValue: [
      {
        value: "3562.48",
        time: "1"
      }, {
        value: "-1437.56",
        time: "2"
      }, {
        value: "-1437.59",
        time: "3"
      }, {
        value: "-631.409",
        time: "4"
      }, {
        value: "180.232",
        time: "5"
      }, {
        value: "1143.6",
        time: "6"
      }, {
        value: "2200.77",
        time: "7"
      }, {
        value: "3740.69",
        time: "8"
      }, {
        value: "5358.06",
        time: "9"
      }, {
        value: "7282.22",
        time: "10"
      }, {
        value: "9566.02",
        time: "11"
      }, {
        value: "11870.7",
        time: "12"
      }, {
        value: "14688",
        time: "13"
      }],
    name: "_Отчет о прибылях и убытках: Нераспределенная прибыль"
  }, {
    value: "-0.723303",
    timedValue: [
      {
        value: "1.46825",
        time: "1"
      }, {
        value: "1.23125",
        time: "2"
      }, {
        value: "1.14628",
        time: "3"
      }, {
        value: "0.94483",
        time: "4"
      }, {
        value: "0.893722",
        time: "5"
      }, {
        value: "0.635352",
        time: "6"
      }, {
        value: "0.58427",
        time: "7"
      }, {
        value: "0.392683",
        time: "8"
      }, {
        value: "0.197096",
        time: "9"
      }, {
        value: "0.226627",
        time: "10"
      }, {
        value: "0.021157",
        time: "11"
      }, {
        value: "-0.447811",
        time: "12"
      }, {
        value: "-0.723303",
        time: "13"
      }],
    name: "Финансовое состояние: Коэффициент текущей ликвидности"
  }, {
    value: "1.83121",
    timedValue: [
      {
        value: "-0.932018",
        time: "1"
      }, {
        value: "-1.14035",
        time: "2"
      }, {
        value: "-1.18034",
        time: "3"
      }, {
        value: "-1.45709",
        time: "4"
      }, {
        value: "-1.38983",
        time: "5"
      }, {
        value: "-2.14157",
        time: "6"
      }, {
        value: "-2.15057",
        time: "7"
      }, {
        value: "-3.16526",
        time: "8"
      }, {
        value: "-5.98104",
        time: "9"
      }, {
        value: "-4.32093",
        time: "10"
      }, {
        value: "-45.6987",
        time: "11"
      }, {
        value: "3.22264",
        time: "12"
      }, {
        value: "1.83121",
        time: "13"
      }],
    name: "Финансовое состояние: Коэффициент обеспеченности собственными средствами"
  }, {
    value: "0.54198",
    timedValue: [
      {
        value: "0.343273",
        time: "1"
      }, {
        value: "0.288464",
        time: "2"
      }, {
        value: "0.285354",
        time: "3"
      }, {
        value: "0.307822",
        time: "4"
      }, {
        value: "0.329423",
        time: "5"
      }, {
        value: "0.33677",
        time: "6"
      }, {
        value: "0.349176",
        time: "7"
      }, {
        value: "0.383507",
        time: "8"
      }, {
        value: "0.419369",
        time: "9"
      }, {
        value: "0.479012",
        time: "10"
      }, {
        value: "0.544444",
        time: "11"
      }, {
        value: "0.454585",
        time: "12"
      }, {
        value: "0.54198",
        time: "13"
      }],
    name: "Финансовое состояние: Коэффициент обеспеченности финансовых обязательств активами"
  }, {
    value: "0.554342",
    timedValue: [
      {
        value: "0.071011",
        time: "1"
      }, {
        value: "0.453952",
        time: "2"
      }, {
        value: "0.501283",
        time: "3"
      }, {
        value: "0.481086",
        time: "4"
      }, {
        value: "0.47362",
        time: "5"
      }, {
        value: "0.493256",
        time: "6"
      }, {
        value: "0.505709",
        time: "7"
      }, {
        value: "0.492872",
        time: "8"
      }, {
        value: "0.502142",
        time: "9"
      }, {
        value: "0.468583",
        time: "10"
      }, {
        value: "0.459089",
        time: "11"
      }, {
        value: "0.54638",
        time: "12"
      }, {
        value: "0.554342",
        time: "13"
      }],
    name: "Финансовая устойчивость: Коэффициент собственности"
  }, {
    value: "-3.7326",
    timedValue: [
      {
        value: "0.18199",
        time: "1"
      }, {
        value: "-0.927005",
        time: "2"
      }, {
        value: "-1.32207",
        time: "3"
      }, {
        value: "-1.55885",
        time: "4"
      }, {
        value: "-1.54622",
        time: "5"
      }, {
        value: "-2.1784",
        time: "6"
      }, {
        value: "-2.42764",
        time: "7"
      }, {
        value: "-2.70399",
        time: "8"
      }, {
        value: "-3.00238",
        time: "9"
      }, {
        value: "-2.55625",
        time: "10"
      }, {
        value: "-2.73866",
        time: "11"
      }, {
        value: "-3.48975",
        time: "12"
      }, {
        value: "-3.7326",
        time: "13"
      }],
    name: "Финансовая устойчивость: Коэффициент абсолютной ликвидности"
  }, {
    value: "-0.899575",
    timedValue: [
      {
        value: "1.09982",
        time: "1"
      }, {
        value: "0.775922",
        time: "2"
      }, {
        value: "0.720511",
        time: "3"
      }, {
        value: "0.564323",
        time: "4"
      }, {
        value: "0.553203",
        time: "5"
      }, {
        value: "0.305517",
        time: "6"
      }, {
        value: "0.351308",
        time: "7"
      }, {
        value: "0.244579",
        time: "8"
      }, {
        value: "0.094691",
        time: "9"
      }, {
        value: "0.161271",
        time: "10"
      }, {
        value: "-0.034626",
        time: "11"
      }, {
        value: "-0.567271",
        time: "12"
      }, {
        value: "-0.899575",
        time: "13"
      }],
    name: "Финансовая устойчивость: Коэффициент критической (быстрой) ликвидности"
  }, {
    value: "23.0647",
    timedValue: [
      {
        value: "9.42163",
        time: "1"
      }, {
        value: "12.492",
        time: "2"
      }, {
        value: "9.05059",
        time: "3"
      }, {
        value: "13.3344",
        time: "4"
      }, {
        value: "13.8635",
        time: "5"
      }, {
        value: "13.1816",
        time: "6"
      }, {
        value: "10.2511",
        time: "7"
      }, {
        value: "10.9647",
        time: "8"
      }, {
        value: "11.833",
        time: "9"
      }, {
        value: "13.9248",
        time: "10"
      }, {
        value: "16.4168",
        time: "11"
      }, {
        value: "19.4895",
        time: "12"
      }, {
        value: "23.0647",
        time: "13"
      }],
    name: "Рентабельность: Рентабельность продукции по затратам"
  }, {
    value: "0.380509",
    timedValue: [
      {
        value: "0.061741",
        time: "1"
      }, {
        value: "-0.022982",
        time: "2"
      }, {
        value: "-0.023885",
        time: "3"
      }, {
        value: "-0.005338",
        time: "4"
      }, {
        value: "0.006506",
        time: "5"
      }, {
        value: "0.027859",
        time: "6"
      }, {
        value: "0.048387",
        time: "7"
      }, {
        value: "0.08714",
        time: "8"
      }, {
        value: "0.128408",
        time: "9"
      }, {
        value: "0.168519",
        time: "10"
      }, {
        value: "0.242144",
        time: "11"
      }, {
        value: "0.265882",
        time: "12"
      }, {
        value: "0.380509",
        time: "13"
      }],
    name: "Рентабельность: Рентабельность активов предприятия"
  }, {
    value: "0.370819",
    timedValue: [
      {
        value: "0.166205",
        time: "1"
      }, {
        value: "-0.047653",
        time: "2"
      }, {
        value: "-0.047523",
        time: "3"
      }, {
        value: "-0.010091",
        time: "4"
      }, {
        value: "0.012378",
        time: "5"
      }, {
        value: "0.047645",
        time: "6"
      }, {
        value: "0.081824",
        time: "7"
      }, {
        value: "0.138273",
        time: "8"
      }, {
        value: "0.188914",
        time: "9"
      }, {
        value: "0.25546",
        time: "10"
      }, {
        value: "0.331463",
        time: "11"
      }, {
        value: "0.299299",
        time: "12"
      }, {
        value: "0.370819",
        time: "13"
      }],
    name: "Рентабельность: Рентабельность основного капитала"
  }, {
    value: "1.23624",
    timedValue: [
      {
        value: "0.127802",
        time: "1"
      }, {
        value: "-0.095837",
        time: "2"
      }, {
        value: "-0.112867",
        time: "3"
      }, {
        value: "-0.046309",
        time: "4"
      }, {
        value: "0.014029",
        time: "5"
      }, {
        value: "0.088641",
        time: "6"
      }, {
        value: "0.190969",
        time: "7"
      }, {
        value: "0.315337",
        time: "8"
      }, {
        value: "0.493156",
        time: "9"
      }, {
        value: "0.709912",
        time: "10"
      }, {
        value: "0.915926",
        time: "11"
      }, {
        value: "0.869311",
        time: "12"
      }, {
        value: "1.23624",
        time: "13"
      }],
    name: "Рентабельность: Рентабельность собственного капитала"
  }, {
    value: "1.87697",
    timedValue: [
      {
        value: "0.596481",
        time: "1"
      }, {
        value: "-10.4343",
        time: "2"
      }, {
        value: "-12.0082",
        time: "3"
      }, {
        value: "-25.9185",
        time: "4"
      }, {
        value: "95.1736",
        time: "5"
      }, {
        value: "14.9516",
        time: "6"
      }, {
        value: "8.39517",
        time: "7"
      }, {
        value: "4.84869",
        time: "8"
      }, {
        value: "3.57129",
        time: "9"
      }, {
        value: "2.711",
        time: "10"
      }, {
        value: "2.04431",
        time: "11"
      }, {
        value: "2.17296",
        time: "12"
      }, {
        value: "1.87697",
        time: "13"
      }],
    name: "Эффективность фондов: Период окупаемости собственного капитала"
  }
];

module.exports = data;